<?php
$collection = $this->getList();
if ($collection && $collection->getSize() > 0) :
?>
<div class="grid np">
	<div class="hor-scroll">
		<table cellspacing="0" class="data order-tables giftwrap-table">
			<col width="10px" />
			<col />
			<col />
			<col width="30%"/>
			<col />
			<col width="10%" />
			<thead>
				<tr class="headings">
					<th><?php echo $this->__('NO');?></th>
					<th><?php echo $this->__('GIFT BOX');?></th>
					<th><?php echo $this->__('GIFT CARD');?></th>
					<th><?php echo $this->__('CARD MESSAGE');?></th>
					<th><?php echo $this->__('WRAPPED ITEMS');?></th>
					<th class="a-right last"><?php echo $this->__('SUBTOTAL');?></th>
				</tr>
			</thead>
			<tbody>				
			<?php
				$i = 0;
				$items = $this->processGroup($collection);
				foreach ($items as $item) :
					$i++;
					$product = Mage::getModel('catalog/product')->load($item->getProductId());
			?>
			<tr class="<?php echo $i%2?'even':'odd' ?>">
				<td>#<?php echo $i;?></td>
				<td>
					<img src="<?php echo $this->getImage($item->getBoxImage());?>">
					<br/><b><?php echo $this->helper('checkout')->formatPrice($item->getBoxPrice());?></b>
					<br/>
					<a href="<?php echo $this->getUrl('vc_giftwrap/adminhtml_box/edit/', array('id' => $item->getBoxId()));?>"><?php echo $this->__('View detail');?></a>
				</td>
				<td>
					<?php if (strlen(trim($item->getCardPrice())) > 0) :?>
						<img src="<?php echo $this->getImage($item->getCardImage());?>">
						<br/><b><?php echo $this->helper('checkout')->formatPrice($item->getCardPrice());?></b>
						<br/>
						<a href="<?php echo $this->getUrl('vc_giftwrap/adminhtml_card/edit/', array('id' => $item->getCardId()));?>"><?php echo $this->__('View detail');?></a>
					<?php else:?>
						--
					<?php endif;?>
				</td>
				
				<td><?php echo $item->getCardMessage();?></td>
				<td class="giftwrap-icol">
					<?php
					$price = 0.00;
					$groupItem = $item->getGroupItem();
					if (is_array($groupItem) && count($groupItem) > 0) :
						?>
						<table class="giftwrap-itable" border="0">
							<col/>
							<col width="100px" />
							<col width="100px" />
							<thead class="headings">
								<tr>
									<th><?php echo $this->__('Product');?></td>
									<th><?php echo $this->__('Price');?></th>
									<th class="a-center"><?php echo $this->__('Qty');?></td>
								</tr>
							</thead>
							
							<tbody>
							
						<?php
						$j = 0;
						foreach ($groupItem as $itemGroup) :
							$j++;
							$price += $itemGroup['product_qty_shipped'] * $itemGroup['price'];
							?>
							<tr class="<?php echo $j%2?'even':'odd' ?>">
								<td>
									<b><?php echo $itemGroup['product_name'];?></b>
									<div><b>SKU:</b> <?php echo $itemGroup['sku'];?></div>
								</td>
								<td><?php echo $this->helper('checkout')->formatPrice($itemGroup['price']);?></td>
								<td class="a-center"><b><?php echo $itemGroup['product_qty_shipped'];?></b></td>
							</tr>
							<?php
						endforeach;
						?>
							</tbody>
						</table>	
						<?php
					endif;
					?>
				</td>
				
				<td class="a-right last"><b><?php echo $this->helper('checkout')->formatPrice($price);?></b></td>
			</tr>
			<?php
				endforeach;
			?>
			</tbody>
		</table>
	</div>
</div>
<br />

<?php	
endif;
?>