<?php
$collection = $this->getList();
if ($collection && $collection->getSize() > 0) :
?>
<table class="data-table giftwrap-table">
	<col width="10px" />
	<col />
	<col />
	<col />
	<col />
	<col width="10%" />
	<thead>
		<tr>
			<th><?php echo $this->__('NO');?></th>
			<th><?php echo $this->__('GIFT BOX');?></th>
			<th><?php echo $this->__('GIFT CARD');?></th>
			<th><?php echo $this->__('CARD MESSAGE');?></th>
			<th><?php echo $this->__('WRAPPED ITEMS');?></th>
			<th><?php echo $this->__('SUBTOTAL');?></th>
		</tr>
	</thead>
	<tbody>				
	<?php
		$i = 0;
		$items = $this->processGroup($collection);
		foreach ($items as $item) :
			$i++;
			$product = Mage::getModel('catalog/product')->load($item->getProductId());
	?>
	<tr>
		<td>#<?php echo $i;?></td>
		<td>
			<img src="<?php echo $this->getImage($item->getBoxImage());?>">
			<br/><?php echo $this->helper('checkout')->formatPrice($item->getBoxPrice());?>
		</td>
		<td>
			<?php if (strlen(trim($item->getCardPrice())) > 0) :?>
				<img src="<?php echo $this->getImage($item->getCardImage());?>">
				<br/><?php echo $this->helper('checkout')->formatPrice($item->getCardPrice());?>
			<?php else:?>
				--
			<?php endif;?>
		</td>
		<td><?php echo $item->getCardMessage();?></td>
		<td class="giftwrap-icol">
			<?php
			$price = 0.00;
			$groupItem = $item->getGroupItem();
			if (is_array($groupItem) && count($groupItem) > 0) :
				?>
				<table class="giftwrap-itable">
					<col width="80%"/>
					<col />
					<col />
					<thead>
						<tr>
							<th><?php echo $this->__('Product');?></th>
							<th><?php echo $this->__('Price');?></th>
							<th><?php echo $this->__('Qty Shipped');?></th>
						</tr>
					</thead>
					<tbody>
					
				<?php
				$i = 0;
				$tRow = count($groupItem);
				foreach ($groupItem as $itemGroup) :
					$i++;
					$price += $itemGroup['product_qty'] * $itemGroup['price'];
					?>
					<tr class="<?php echo $i%2?'even':'odd' ?> <?php echo ($i == $tRow ? 'last' : '');?>">
						<td class="product-cart-info">
							<h2 class="product-name"><?php echo $itemGroup['product_name'];?></h2>
							<div class="product-cart-sku"><span class="label">SKU:</span> <?php echo $itemGroup['sku'];?></div>
						</td>
						<td><?php echo $this->helper('checkout')->formatPrice($itemGroup['price']);?></td>
						<td class="a-center"><?php echo $this->__('Shipped:');?> <b><?php echo $itemGroup['product_qty'];?></b></td>
					</tr>
					<?php
				endforeach;
				?>
					</tbody>
				</table>	
				<?php
			endif;
			?>
		</td>
		<td><?php echo $this->helper('checkout')->formatPrice($price);?></td>
    </td>

	</tr>
	<?php
		endforeach;
	?>
	</tbody>
</table>
<?php	
endif;
?>